### ISSUE TITLE
Error with usrClass.dat hive

### ISSUE THREAD

**Issue by muteb** [janstarke/nt-hive2#10]
Hi Jan,

Sometimes I face an error with this hive "usrclass.dat" and I tried to trouble shoot it but I couldn't spot the actual error.

Here is the printout error of the terminal once executed:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { pos: 0x0, err: Any { .. } }', C:\Users\user\Documents\rust\nt-hive2\src\hive\hive_struct.rs:246:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src/result.rs:1107:23
   4: nt_hive2::hive::hive_struct::Hive<B,nt_hive2::hive::hive_status::CleanHive>::read_structure
             at .\src\hive\hive_struct.rs:246:33
   5: nt_hive2::nk::KeyNode::read_subkeys::{{closure}}
             at .\src\nk.rs:204:44
   6: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\adapters/map.rs:91:28
   7: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\traits/iterator.rs:2238:21
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\adapters/map.rs:117:9
   9: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\adapters/mod.rs:195:9
  10: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\traits/iterator.rs:2299:9
  11: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\adapters/mod.rs:178:9
  12: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\alloc\src\vec/mod.rs:2749:35
  13: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\alloc\src\vec/spec_extend.rs:18:9
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\alloc\src\vec/spec_from_iter_nested.rs:43:9
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\alloc\src\vec/spec_from_iter.rs:33:9
  16: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\alloc\src\vec/mod.rs:2649:9
  17: core::iter::traits::iterator::Iterator::collect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\traits/iterator.rs:1836:9
  18: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src/result.rs:2072:49
  19: core::iter::adapters::try_process
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\adapters/mod.rs:164:17
  20: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src/result.rs:2072:9
  21: core::iter::traits::iterator::Iterator::collect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\iter\traits/iterator.rs:1836:9
  22: nt_hive2::nk::KeyNode::read_subkeys
             at .\src\nk.rs:203:46
  23: nt_hive2::nk::KeyNode::subkeys
             at .\src\nk.rs:160:22
  24: nt_hive2::main
             at .\src\main.rs:13:15
  25: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by janstarke** [comment]
Hello,

could you please provide a sample file which causes this error to me?

Regards, Jan

**Comment by janstarke** [comment]
I created a branch for this issue and added a more usable error message in `read_structure()`

**Comment by muteb** [comment]
Hi Jan,

well, it only happens on my own use windows 11 system and afraid that I can't share the file as it might private info.

I will try to simulate the same machine on a vm and hopefully I can catch such error.

**Comment by muteb** [comment]
Hi Jan,
Upon troubleshooting the error, I identified the offset at which the error initiates. When this offset is passed to the Cell struct "hive_struct.rs:246:48", the app crashes with previous error. I have successfully dumped 256 bytes of data starting from the identified offset and attached the relevant file herewith.
[3509136.zip](https://github.com/dfir-dd/nt-hive2/files/12768409/3509136.zip)

Keep in mind I dumped 256 and I believe the nk ends at 0050h. I hope this helps and thanks in advance

**Comment by janstarke** [comment]
I tried to write a test case using the data you provided. Unfortunately this is not working, because the field `KeyNode::key_values_list` tries to read data at other parts of the registry file. 

What does `nt_hive2` print when you try to parse your file with the modified code that I commited in the branch `10-error-with-usrclassdat-hive`? There should be a more descriptive error message

**Comment by muteb** [comment]
Yes, I tried it and still giving me the same error pos:0x0, however,I printed out the error in line 253 hive_struct.rs and it then jumped to the hex editor to see the actual values. The values are all zeros as showing on the attached picture
>>>>> Error while reading from offset 00359b90: Custom { pos: 0x0, err: Any { .. } }<<
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { pos: 0x0, err: Any { .. } }', src\testerror.rs:14:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src/result.rs:1076:23
   4: nt_hive2::testerror
             at .\src\testerror.rs:14:15
   5: core::ops::function::FnOnce::call_on
![Screenshot 2023-10-02 231115](https://github.com/dfir-dd/nt-hive2/assets/5000589/7093d9f1-9e6b-4ab9-bf17-aa68cc24f1c1)
ce
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by janstarke** [comment]
I'm not happy with the error reporting code, which obviously does not help us in isolating the problem. So I added a new log output in `hive_struct.rs`: https://github.com/dfir-dd/nt-hive2/blob/78c3112a59ea968c1c0f404ee190516554cafa0e/src/hive/hive_struct.rs#L257-L259 There seems to be that an error has occurred somewhere else and has been wrapped in a `BinRead::Error` and we could not obtain the wrapped information until now. 

Can you please check if my change made a difference with your data?

**Comment by janstarke** [comment]
I investigated a little more and I assume that your test data contains an invalid key name:
![grafik](https://github.com/dfir-dd/nt-hive2/assets/7724055/f05592a9-3613-454b-88ca-99dc24beeedc)
The error occurs when we try to decode the bytes:
https://github.com/dfir-dd/nt-hive2/blob/12280bcd2cfcdbad539ff3a79895d1cbee20bc5f/src/util.rs#L21-L29
So, the question is: How should we handle non-printable strings?

**Comment by muteb** [comment]
I believe the class BinaryString  is very interesting and well handled non-printable strings.  I can't add more to what you have done. thanks alot.

**Comment by janstarke** [comment]
Thanks for your feedback. I will incorporate the changes into `main` as soon as I'm back from my current trip.

In this case, I was using ImHex (https://github.com/WerWolv/ImHex), because it helps me to parse binary data visually.

Regards, Jan
